services:
    # Generic Declaration
    Spipu\UserBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,SpipuUserBundle.php}'
        autowire: true
        autoconfigure: true

    # API Services
    Spipu\UserBundle\Service\MailConfigurationInterface:
        class:  Spipu\UserBundle\Service\MailConfiguration
        public: true

    Spipu\UserBundle\Repository\UserRepository:
        tags: ['doctrine.repository_service']
        arguments:
            - '@doctrine'
            - '@Spipu\UserBundle\Service\ModuleConfigurationInterface'

    # Role Definition
    Spipu\UserBundle\Service\RoleDefinition:
        public: true
        tags: ['spipu.user.role']

    # Fixture
    Spipu\UserBundle\Fixture\FirstUserFixture:
        tags: ['spipu.fixture']
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
            - '@Spipu\UserBundle\Service\ModuleConfigurationInterface'
            - '@Spipu\UserBundle\Repository\UserRepository'

    # Internal Services
    Spipu\UserBundle\Service\UserTokenManager:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '%kernel.secret%'

    Spipu\UserBundle\Ui\CreationForm:
        arguments:
            - '@Spipu\UserBundle\Service\ModuleConfigurationInterface'
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    Spipu\UserBundle\Ui\NewPasswordForm:
        arguments:
            - '@Spipu\UserBundle\Service\ModuleConfigurationInterface'
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    Spipu\UserBundle\Ui\PasswordForm:
        arguments:
            - '@Spipu\UserBundle\Service\ModuleConfigurationInterface'
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    Spipu\UserBundle\Ui\ProfileForm:
        arguments:
            - '@Spipu\UserBundle\Service\ModuleConfigurationInterface'

    Spipu\UserBundle\Ui\RecoveryForm:
        arguments:
            - '@Spipu\UserBundle\Service\ModuleConfigurationInterface'

    Spipu\UserBundle\Ui\UserGrid:
        arguments:
            - '@Spipu\UserBundle\Service\ModuleConfigurationInterface'
            - '@security.token_storage'
            - '@Spipu\UiBundle\Form\Options\YesNo'
