services:
    # Generic Declaration
    Spipu\UserBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,SpipuUserBundle.php}'
        autowire: true
        autoconfigure: true

    # API Services
    Spipu\UserBundle\Service\MailConfigurationInterface:
        class:  Spipu\UserBundle\Service\MailConfiguration
        public: true
        autowire: true

    Spipu\UserBundle\Repository\UserRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    # Role Definition
    Spipu\UserBundle\Service\RoleDefinition:
        public: true
        tags: ['spipu.user.role']

    # Fixture
    Spipu\UserBundle\Fixture\FirstUserFixture:
        autowire: true
        tags: ['spipu.fixture']

    # Internal Services
    Spipu\UserBundle\Service\UserTokenManager:
        autowire: true
        arguments:
            $keySecret: '%kernel.secret%'

