# This file is part of a Spipu Bundle
#
# (c) Laurent Minguet
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
controllers:
    resource: '../src/Controller/'
    type:     attribute
    prefix:   /
    trailing_slash_on_root: false