# This file is part of a Spipu Bundle
#
# (c) Laurent Minguet
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
services:
    # Generic Declaration
    Spipu\UserBundle\:
        resource: '../src/*'
        exclude: '../src/{Entity,SpipuUserBundle.php}'
        autowire: true
        autoconfigure: true

    # API Services
    Spipu\UserBundle\Service\MailConfigurationInterface:
        class:  Spipu\UserBundle\Service\MailConfiguration
        public: true
        autowire: true

    Spipu\UserBundle\Repository\UserRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    # Role Definition
    Spipu\UserBundle\Service\RoleDefinition:
        public: true
        tags: ['spipu.user.role']

    # Fixture
    Spipu\UserBundle\Fixture\FirstUserFixture:
        autowire: true
        tags: ['spipu.fixture']

    # Internal Services
    Spipu\UserBundle\Service\UserTokenManager:
        autowire: true
        arguments:
            $keySecret: '%kernel.secret%'

